### ISSUE TITLE
Augment README with WebApp Deployment Instructions

### ISSUE THREAD

**Issue by theyiwenliu** [chrismattmann/shangridocs#1]
Now I try to use Shangrila and this is what I have after uploading a pdf for testing:
![extraction](https://cloud.githubusercontent.com/assets/10496910/9894400/649955d2-5bd8-11e5-846a-8d14b28a15a2.png)

We need to document which other services need to be running before Shangrlia Docs Web App runs properly. There are prerequisites which we need to clarify and document within the source code README(s).

**Comment by chrismattmann** [comment]
See updated README and recent commits.
