### ISSUE TITLE
Remove references to CG

### ISSUE THREAD

**Issue by rtapella** [chrismattmann/shangridocs#2]
1. Remove directories with "celgene" in them.
2. Remove "celgene" from the content of files. 

I see it in 
- file path celgene-shangrila
- HomePage.html in shangridocs-webapp src
- index.jsp in shangridocs-webass src
- pom.xml in shangridocs-webapp

**Comment by chrismattmann** [comment]
Thanks Rob, will do. I am not seeing a celgene-shangrila folder (see the convert-wicket branch) Can you comment?

**Comment by rtapella** [comment]
Yeah I don't see it now either.

**Comment by chrismattmann** [comment]
Great OK I think this is done.
